#Requires AutoHotkey v2.0

WriteValueToFile(filePath, content) { ; ghi file
    FileAppend(content "`n", filePath) ; Thêm nội dung vào file
}

GenerateConfigFile(){
    If !FileExist(filePath.cus) || FileGetSize(filePath.cus) = 0 {
        if FileExist(filePath.cus) ; Kiểm tra sự tồn tại trước khi xóa
            FileDelete(filePath.cus) ; Xóa file nếu có nhưng trống
        FileAppend("", filePath.cus) ; Tạo file mới
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, 'path to AutoHotkey.exe file')
        WriteValueToFile(filePath.cus, 'AHKfilePath := "C:\Program Files\AutoHotkey\v2\AutoHotkey.exe"')
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, 'path to RobloxPlayerBeta.exe file')
        WriteValueToFile(filePath.cus, 'robloxPath := auto')
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "Mouse position on screen at last played game position")
        WriteValueToFile(filePath.cus, "x1 := 0")
        WriteValueToFile(filePath.cus, "y1 := 0")
        WriteValueToFile(filePath.cus, "c1 := 0x202227")
        WriteValueToFile(filePath.cus, "Mouse position at play game button")
        WriteValueToFile(filePath.cus, "x2 := 0")
        WriteValueToFile(filePath.cus, "y2 := 0")
        WriteValueToFile(filePath.cus, "c2 := 0x00B06F")
        WriteValueToFile(filePath.cus, "c21 := 0x009F64")
        WriteValueToFile(filePath.cus, "mouse position on white text in private game option")
        WriteValueToFile(filePath.cus, "x3 := 0")
        WriteValueToFile(filePath.cus, "y3 := 0")
        WriteValueToFile(filePath.cus, "c3 := 0xFFFFFF")
        WriteValueToFile(filePath.cus, "mouse position at the green text in career mode option")
        WriteValueToFile(filePath.cus, "x4 := 0")
        WriteValueToFile(filePath.cus, "y4 := 0")
        WriteValueToFile(filePath.cus, "c4 := 0x00A5FF")
        WriteValueToFile(filePath.cus, "c41 := 0x00527F")
        WriteValueToFile(filePath.cus, "Mouse position on the white text in the private game creation button")
        WriteValueToFile(filePath.cus, "x5 := 0")
        WriteValueToFile(filePath.cus, "y5 := 0")
        WriteValueToFile(filePath.cus, "c5 := 0xFFFFFF")
        WriteValueToFile(filePath.cus, "mouse position on white text in play button")
        WriteValueToFile(filePath.cus, "x6 := 0")
        WriteValueToFile(filePath.cus, "y6 := 0")
        WriteValueToFile(filePath.cus, "c6 := 0xFFFFFF")
        WriteValueToFile(filePath.cus, "Mouse position at the white text in the Ready button (recommended to choose the letter R to avoid being recognized as counting kills)")
        WriteValueToFile(filePath.cus, "x7 := 0")
        WriteValueToFile(filePath.cus, "y7 := 0")
        WriteValueToFile(filePath.cus, "c7 := 0xA6A6A6")
        WriteValueToFile(filePath.cus, "Position the mouse on the white text in the view change button (right arrow)")
        WriteValueToFile(filePath.cus, "x8 := 0")
        WriteValueToFile(filePath.cus, "y8 := 0")
        WriteValueToFile(filePath.cus, "c8 := 0xFFFFFF")
        WriteValueToFile(filePath.cus, "Mouse position at yellow text when receiving first round reward (recommended not to use perk that can change the amount received in first round)")
        WriteValueToFile(filePath.cus, "x9 := 0")
        WriteValueToFile(filePath.cus, "y9 := 0")
        WriteValueToFile(filePath.cus, "c9 := 0xFFB400")
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "4 desired mouse positions to set Normal gear")
        WriteValueToFile(filePath.cus, "x10 := 0")
        WriteValueToFile(filePath.cus, "y10 := 0")
        WriteValueToFile(filePath.cus, "x11 := 0")
        WriteValueToFile(filePath.cus, "y11 := 0")
        WriteValueToFile(filePath.cus, "x12 := 0")
        WriteValueToFile(filePath.cus, "y12 := 0")
        WriteValueToFile(filePath.cus, "x13 := 0")
        WriteValueToFile(filePath.cus, "y13 := 0")
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "4 positions on the screen will have black space when losing the match")
        WriteValueToFile(filePath.cus, "x14 := 0")
        WriteValueToFile(filePath.cus, "y14 := 0")
        WriteValueToFile(filePath.cus, "x15 := 0")
        WriteValueToFile(filePath.cus, "y15 := 0")
        WriteValueToFile(filePath.cus, "x16 := 0")
        WriteValueToFile(filePath.cus, "y16 := 0")
        WriteValueToFile(filePath.cus, "x17 := 0")
        WriteValueToFile(filePath.cus, "y17 := 0")
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "11 mouse positions to upgrade shop")
        WriteValueToFile(filePath.cus, "xshop1 := ")
        WriteValueToFile(filePath.cus, "yshop1 := ")
        WriteValueToFile(filePath.cus, "xshop2 := ")
        WriteValueToFile(filePath.cus, "yshop2 := ")
        WriteValueToFile(filePath.cus, "xshop3 := ")
        WriteValueToFile(filePath.cus, "yshop3 := ")
        WriteValueToFile(filePath.cus, "xshop4 := ")
        WriteValueToFile(filePath.cus, "yshop4 := ")
        WriteValueToFile(filePath.cus, "xshop5 := ")
        WriteValueToFile(filePath.cus, "yshop5 := ")
        WriteValueToFile(filePath.cus, "xshop6 := ")
        WriteValueToFile(filePath.cus, "yshop6 := ")
        WriteValueToFile(filePath.cus, "xshop7 := ")
        WriteValueToFile(filePath.cus, "yshop7 := ")
        WriteValueToFile(filePath.cus, "xshop8 := ")
        WriteValueToFile(filePath.cus, "yshop8 := ")
        WriteValueToFile(filePath.cus, "xshop9 := ")
        WriteValueToFile(filePath.cus, "yshop9 := ")
        WriteValueToFile(filePath.cus, "xshop10 := ")
        WriteValueToFile(filePath.cus, "yshop10 := ")
        WriteValueToFile(filePath.cus, "xshopnext := ")
        WriteValueToFile(filePath.cus, "yshopnext := ")
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "Position the mouse on the screen at the position of special gear 2 (recommended in the middle of the character)")
        WriteValueToFile(filePath.cus, "xs2 := 0")
        WriteValueToFile(filePath.cus, "ys2 := 0")
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "doorDis := 2310")
        WriteValueToFile(filePath.cus, "CusdoorDis := 2110")
        WriteValueToFile(filePath.cus, "centerDis := 2440")
        WriteValueToFile(filePath.cus, "maxDis(cDis) := 30")
        WriteValueToFile(filePath.cus, "Robloxopentimeoutvar := 15000")
        WriteValueToFile(filePath.cus, "CustomModetimeoutvar := 7200000")
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "GearModeKeyBind := B")
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "RechargeNormalGear1st := 10")
        WriteValueToFile(filePath.cus, "RechargeNormalGear2nd := 14")
        WriteValueToFile(filePath.cus, "RechargeNormalGear3rd := 18")
        WriteValueToFile(filePath.cus, "RechargeNormalGear4th := 21")
        WriteValueToFile(filePath.cus, "RechargeNormalGear5th := 26")
        WriteValueToFile(filePath.cus, "RechargeSpecialGear1 := 17")
        WriteValueToFile(filePath.cus, "ShopUpgradeRound := 21")
        WriteValueToFile(filePath.cus, '---')
        WriteValueToFile(filePath.cus, "xMode1 := 0")
        WriteValueToFile(filePath.cus, "yMode1 := 0")
        WriteValueToFile(filePath.cus, "xMode2 := 0")
        WriteValueToFile(filePath.cus, "yMode2 := 0")
    }
}


If !FileExist(filePath.his){
    FileAppend("", filePath.his) ; Tạo file mới
}